import type { Metadata } from "next";
import { Inter, Libre_Baskerville, Roboto } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar,{Navigation} from "@/Navbar";
import Topbar from "@/Topbar";

// const inter = Inter({ subsets: ["latin"] });
const libreBaskerville = Libre_Baskerville({subsets: ['latin'], weight: "700"});
const roboto = Roboto({subsets: ['latin'], weight: "400"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const navigation: Navigation = {
  home:   { path: "/",        displayName: "Home" },
  hero:   { path: "/hero",    displayName: "Hero" },
  test:   { path: "/test",    displayName: "Test" },
  about:  { path: "/about",   displayName: "404" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className} suppressHydrationWarning>
        <Providers>
          {/*  </Navbar> */}
          <Topbar />
          <Navbar navigation={navigation} />
          {children}
        </Providers>
        </body>
    </html>
  );
}
